--Tabla temporal #LOCALIDADES1.
CREATE TABLE #LOCALIDADES1
(
	idrow int identity PRIMARY KEY,
	idprovincia int, 
	idlocalidad int, 
	descripcion varchar(50),
)

--Lote de datos a insertar en la tabla temporal #LOCALIDADES1.
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (1, 1, 'Ciudad Autónoma de Buenos Aires')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (1, 2, 'Colegiales')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (1, 3, 'Retiro')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (1, 4, 'Villa Lugano')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (1, 5, 'Villa Santa Rita')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 1, 'Adrogué')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 2, 'Alberti')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 3, 'Arrecifes')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 4, 'Avellaneda')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 5, 'Ayacucho')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 6, 'Azul')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 7, 'Bahía Blanca')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 8, 'Balcarce')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 9, 'Baradero')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 10, 'Belén de Escobar')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 11, 'Benito Juárez')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 12, 'Berisso')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 13, 'Bragado')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 14, 'Brandsen')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 15, 'Campana')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 16, 'Cañuelas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 17, 'Capilla del Señor')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 18, 'Capitán Sarmiento')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 19, 'Carhué')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 20, 'Cariló')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 21, 'Carlos Casares')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 22, 'Carlos Tejedor')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 23, 'Carmen de Areco')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 24, 'Carmen de Patagones')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 25, 'Caseros')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 26, 'Castelli')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 27, 'Chacabuco')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 28, 'Chascomús')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 29, 'Chivilcoy')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 30, 'Colón')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 31, 'Coronel Dorrego')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 32, 'Coronel Pringles')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 33, 'Coronel Suárez')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 34, 'Coronel Vidal')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 35, 'Daireaux')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 36, 'Dolores')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 37, 'Ensenada')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 38, 'Ezeiza')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 39, 'Florencio Varela')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 40, 'Florentino Ameghino')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 41, 'General Alvear')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 42, 'General Arenales')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 43, 'General Belgrano')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 44, 'General Conesa')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 45, 'General Guido')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 46, 'General Juan Madariaga')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 47, 'General La Madrid')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 48, 'General Las Heras')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 49, 'General Lavalle')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 50, 'General Pinto')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 51, 'General Rodríguez')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 52, 'General San Martín')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 53, 'General Viamonte')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 54, 'General Villegas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 55, 'Guaminí')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 56, 'Guernica')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 57, 'Henderson')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 58, 'Hurlingham')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 59, 'Ituzaingó')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 60, 'Junín')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 61, 'La Plata')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 62, 'Lanús')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 63, 'Laprida')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 64, 'Las Flores')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 65, 'Lincoln')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 66, 'Lobería')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 67, 'Lobos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 68, 'Lomas de Zamora')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 69, 'Luján')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 70, 'Magdalena')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 71, 'Maipú')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 72, 'Mar del Plata')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 73, 'Mar del Tuyú')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 74, 'Marcos Paz')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 75, 'Médanos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 76, 'Mercedes')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 77, 'Merlo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 78, 'Miramar')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 79, 'Monte Hermoso')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 80, 'Morón')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 81, 'Navarro')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 82, 'Necochea')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 83, 'Nueve de Julio')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 84, 'Olavarría')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 85, 'Olivos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 86, 'Pehuajó')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 87, 'Pellegrini')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 88, 'Pergamino')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 89, 'Pigüé')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 90, 'Pila')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 91, 'Pilar')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 92, 'Pinamar')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 93, 'Pontevedra')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 94, 'Puan')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 95, 'Punta Alta')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 96, 'Quilmes')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 97, 'Ramallo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 98, 'Ranchos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 99, 'Rauch')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 100, 'Rojas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 101, 'Roque Pérez')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 102, 'Saladillo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 103, 'Salliqueló')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 104, 'Salto')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 105, 'San Andrés de Giles')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 106, 'San Antonio de Areco')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 107, 'San Carlos de Bolívar')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 108, 'San Cayetano')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 109, 'San Clemente del Tuyú')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 110, 'San Isidro')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 111, 'San Justo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 112, 'San Miguel del Monte')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 113, 'San Nicolás de los Arroyos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 114, 'San Pedro')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 115, 'San Vicente')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 116, 'Santa Catalina - Dique Lujan')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 117, 'Suipacha')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 118, 'Tandil')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 119, 'Tapalqué')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 120, 'Tigre')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 121, 'Tornquist')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 122, 'Trenque Lauquen')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 123, 'Tres Arroyos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 124, 'Tres Lomas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 125, 'Vedia')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 126, 'Veinticinco de Mayo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 127, 'Verónica')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 128, 'Villa Gesell')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (2, 129, 'Zárate')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 1, 'Ancasti')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 2, 'Andalgalá')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 3, 'Antofagasta de la Sierra')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 4, 'Bañado de Ovanta')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 5, 'Belén')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 6, 'Capayán')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 7, 'Chumbicha')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 8, 'El Alto')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 9, 'El Rodeo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 10, 'Esquiú')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 11, 'Fiambalá')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 12, 'Hualfín')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 13, 'Huillapima')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 14, 'Icaño')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 15, 'La Merced')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 16, 'La Puerta')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 17, 'La Puerta de San José')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 18, 'Londres')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 19, 'Los Altos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 20, 'Los Varela')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 21, 'Mutquín')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 22, 'Pomán')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 23, 'Puerta de Corral Quemado')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 24, 'Recreo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 25, 'San Antonio')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 26, 'San Antonio')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 27, 'San Fernando del Valle de Catamarca')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 28, 'San Isidro')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 29, 'San José')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 30, 'Santa María')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 31, 'Saujil')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (3, 32, 'Tinogasta')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 1, 'Aviá Terai')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 2, 'Barranqueras')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 3, 'Basail')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 4, 'Campo Largo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 5, 'Capitán Solari')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 6, 'Castelli')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 7, 'Charadai')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 8, 'Charata')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 9, 'Chorotis')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 10, 'Ciervo Petiso')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 11, 'Colonia Benítez')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 12, 'Colonia Elisa')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 13, 'Colonias Unidas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 14, 'Concepción del Bermejo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 15, 'Coronel Du Graty')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 16, 'Corzuela')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 17, 'Coté-Lai')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 18, 'Fontana')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 19, 'Gancedo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 20, 'General José de San Martín')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 21, 'General Pinedo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 22, 'General Vedia')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 23, 'Hermoso Campo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 24, 'La Clotilde')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 25, 'La Eduvigis')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 26, 'La Escondida')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 27, 'La Leonesa')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 28, 'La Tigra')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 29, 'La Verde')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 30, 'Laguna Limpia')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 31, 'Lapachito')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 32, 'Las Breñas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 33, 'Las Garcitas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 34, 'Los Frentones')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 35, 'Machagai')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 36, 'Makallé')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 37, 'Margarita Belén')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 38, 'Napenay')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 39, 'Pampa Almirón')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 40, 'Pampa del Indio')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 41, 'Pampa del Infierno')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 42, 'Presidencia de la Plaza')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 43, 'Presidencia Roca')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 44, 'Presidencia Roque Sáenz Peña')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 45, 'Puerto Bermejo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 46, 'Puerto Tirol')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 47, 'Puerto Vilelas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 48, 'Quitilipi')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 49, 'Resistencia')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 50, 'Samuhú')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 51, 'San Bernardo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 52, 'Santa Sylvina')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 53, 'Taco Pozo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 54, 'Tres Isletas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 55, 'Villa Ángela')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (4, 56, 'Villa Berthet')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 1, 'Alto Río Senguer')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 2, 'Camarones')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 3, 'Comodoro Rivadavia')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 4, 'Dolavón')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 5, 'El Maitén')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 6, 'Esquel')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 7, 'Gaimán')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 8, 'Gastre')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 9, 'Gobernador Costa')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 10, 'Hoyo de Epuyén')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 11, 'José de San Martín')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 12, 'Lago Puelo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 13, 'Las Plumas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 14, 'Leleque')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 15, 'Paso de Indios')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 16, 'Puerto Madryn')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 17, 'Rada Tilly')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 18, 'Rawson')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 19, 'Río Mayo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 20, 'Río Pico')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 21, 'Sarmiento')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 22, 'Tecka')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 23, 'Telsen')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 24, 'Trelew')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (5, 25, 'Trevelin')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 1, 'Achiras')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 2, 'Adelia María')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 3, 'Agua de Oro')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 4, 'Alejandro Roca')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 5, 'Alejo Ledesma')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 6, 'Almafuerte')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 7, 'Alta Gracia')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 8, 'Altos de Chipión')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 9, 'Arias')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 10, 'Arroyito')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 11, 'Arroyo Cabral')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 12, 'Balnearia')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 13, 'Bell Ville')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 14, 'Berrotarán')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 15, 'Brinkmann')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 16, 'Buchardo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 17, 'Camilo Aldao')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 18, 'Canals')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 19, 'Cañada de Luque')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 20, 'Capilla del Monte')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 21, 'Carnerillo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 22, 'Carrilobo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 23, 'Cavanagh')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 24, 'Charras')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 25, 'Chazón')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 26, 'Cintra')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 27, 'Colonia La Tordilla')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 28, 'Colonia San Bartolomé')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 29, 'Córdoba')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 30, 'Coronel Baigorria')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 31, 'Coronel Moldes')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 32, 'Corral de Bustos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 33, 'Corralito')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 34, 'Cosquín')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 35, 'Costa Sacate')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 36, 'Cruz Alta')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 37, 'Cruz del Eje')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 38, 'Cuesta Blanca')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 39, 'Dalmacio Vélez Sársfield')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 40, 'Deán Funes')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 41, 'Del Campillo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 42, 'Despeñaderos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 43, 'Devoto')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 44, 'Dolores')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 45, 'El Arañado')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 46, 'El Tío')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 47, 'Elena')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 48, 'Embalse')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 49, 'Etruria')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 50, 'General Baldissera')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 51, 'General Cabrera')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 52, 'General Levalle')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 53, 'General Roca')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 54, 'Guatimozín')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 55, 'Hernando')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 56, 'Huanchillas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 57, 'Huerta Grande')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 58, 'Huinca Renancó')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 59, 'Idiazábal')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 60, 'Inriville')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 61, 'Isla Verde')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 62, 'Italó')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 63, 'James Craik')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 64, 'Jesús María')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 65, 'Justiniano Posse')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 66, 'La Calera')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 67, 'La Carlota')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 68, 'La Cesira')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 69, 'La Cumbre')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 70, 'La Falda')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 71, 'La Francia')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 72, 'La Granja')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 73, 'La Para')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 74, 'La Playosa')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 75, 'Laborde')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 76, 'Laboulaye')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 77, 'Laguna Larga')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 78, 'Las Acequias')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 79, 'Las Higueras')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 80, 'Las Junturas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 81, 'Las Perdices')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 82, 'Las Varas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 83, 'Las Varillas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 84, 'Leones')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 85, 'Los Cóndores')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 86, 'Los Surgentes')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 87, 'Malagueño')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 88, 'Malvinas Argentinas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 89, 'Marcos Juárez')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 90, 'Marull')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 91, 'Mattaldi')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 92, 'Mendiolaza')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 93, 'Mina Clavero')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 94, 'Miramar')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 95, 'Monte Buey')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 96, 'Monte Cristo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 97, 'Monte Maíz')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 98, 'Morrison')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 99, 'Morteros')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 100, 'Noetinger')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 101, 'Obispo Trejo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 102, 'Oliva')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 103, 'Oncativo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 104, 'Ordóñez')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 105, 'Pascanas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 106, 'Pasco')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 107, 'Pilar')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 108, 'Piquillín')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 109, 'Porteña')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 110, 'Pozo del Molle')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 111, 'Quilino')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 112, 'Río Ceballos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 113, 'Río Cuarto')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 114, 'Río Segundo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 115, 'Río Tercero')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 116, 'Sacanta')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 117, 'Saldán')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 118, 'Salsacate')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 119, 'Salsipuedes')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 120, 'Sampacho')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 121, 'San Agustín')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 122, 'San Antonio de Litín')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 123, 'San Basilio')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 124, 'San Carlos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 125, 'San Francisco')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 126, 'San Francisco del Chañar')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 127, 'San José de la Dormida')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 128, 'Santa Eufemia')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 129, 'Santa Magdalena')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 130, 'Santa Rosa de Calamuchita')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 131, 'Santa Rosa de Río Primero')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 132, 'Santiago Temple')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 133, 'Saturnino M. Laspiur')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 134, 'Sebastián Elcano')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 135, 'Serrano')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 136, 'Serrezuela')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 137, 'Tancacha')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 138, 'Ticino')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 139, 'Tío Pujio')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 140, 'Toledo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 141, 'Ucacha')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 142, 'Unquillo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 143, 'Valle Hermoso')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 144, 'Viamonte')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 145, 'Vicuña Mackenna')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 146, 'Villa Allende')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 147, 'Villa Ascasubi')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 148, 'Villa Berna')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 149, 'Villa Carlos Paz')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 150, 'Villa Concepción del Tío')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 151, 'Villa Cura Brochero')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 152, 'Villa de María')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 153, 'Villa de Soto')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 154, 'Villa del Dique')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 155, 'Villa del Rosario')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 156, 'Villa del Totoral')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 157, 'Villa Dolores')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 158, 'Villa General Belgrano')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 159, 'Villa Giardino')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 160, 'Villa Huidobro')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 161, 'Villa Las Rosas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 162, 'Villa María')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 163, 'Villa Nueva')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 164, 'Villa Reducción')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 165, 'Villa Rumipal')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 166, 'Villa Tulumba')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 167, 'Villa Valeria')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (6, 168, 'Wenceslao Escalante')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 1, 'Alvear')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 2, 'Bella Vista')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 3, 'Berón de Astrada')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 4, 'Bonpland')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 5, 'Chavarría')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 6, 'Concepción')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 7, 'Corrientes')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 8, 'Cruz de los Milagros')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 9, 'Curuzú Cuatiá')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 10, 'Empedrado')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 11, 'Esquina')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 12, 'Felipe Yofré')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 13, 'Garruchos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 14, 'Gobernador Ingeniero Valentín Virasoro')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 15, 'Gobernador Juan E. Martínez')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 16, 'Goya')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 17, 'Herlitzka')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 18, 'Itá Ibaté')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 19, 'Itatí')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 20, 'Ituzaingó')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 21, 'Juan Pujol')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 22, 'La Cruz')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 23, 'Libertad')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 24, 'Lomas de Vallejos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 25, 'Loreto')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 26, 'Mariano I. Loza')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 27, 'Mburucuyá')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 28, 'Mercedes')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 29, 'Mocoretá')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 30, 'Monte Caseros')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 31, 'Nuestra Señora del Rosario de Caa Catí')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 32, 'Nueve de Julio')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 33, 'Palmar Grande')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 34, 'Paso de la Patria')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 35, 'Paso de los Libres')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 36, 'Pedro R. Fernández')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 37, 'Perugorría')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 38, 'Pueblo Libertador')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 39, 'Riachuelo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 40, 'Saladas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 41, 'San Carlos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 42, 'San Cosme')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 43, 'San Lorenzo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 44, 'San Luis del Palmar')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 45, 'San Miguel')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 46, 'San Roque')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 47, 'Santa Lucía')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 48, 'Santa Rosa')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 49, 'Santo Tomé')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 50, 'Sauce')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 51, 'Yapeyú')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (7, 52, 'Yataity Calle')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 1, 'Aldea San Antonio')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 2, 'Aranguren')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 3, 'Bovril')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 4, 'Caseros')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 5, 'Ceibas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 6, 'Chajarí')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 7, 'Colón')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 8, 'Colonia Elía')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 9, 'Concepción del Uruguay')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 10, 'Concordia')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 11, 'Conscripto Bernardi')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 12, 'Crespo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 13, 'Diamante')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 14, 'Domínguez')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 15, 'Federación')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 16, 'Federal')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 17, 'General Campos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 18, 'General Galarza')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 19, 'General Ramírez')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 20, 'Gobernador Mansilla')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 21, 'Gualeguay')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 22, 'Gualeguaychú')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 23, 'Hasenkamp')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 24, 'Hernández')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 25, 'Herrera')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 26, 'La Criolla')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 27, 'La Paz')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 28, 'Larroque')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 29, 'Los Charrúas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 30, 'Los Conquistadores')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 31, 'Lucas González')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 32, 'Maciá')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 33, 'Nogoyá')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 34, 'Oro Verde')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 35, 'Paraná')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 36, 'Piedras Blancas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 37, 'Pronunciamiento')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 38, 'Puerto Ibicuy')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 39, 'Puerto Yeruá')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 40, 'Rosario del Tala')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 41, 'San Benito')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 42, 'San Gustavo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 43, 'San José de Feliciano')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 44, 'San Justo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 45, 'San Salvador')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 46, 'Santa Ana')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 47, 'Santa Anita')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 48, 'Santa Elena')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 49, 'Sauce de Luna')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 50, 'Seguí')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 51, 'Tabossi')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 52, 'Ubajay')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 53, 'Urdinarrain')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 54, 'Viale')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 55, 'Victoria')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 56, 'Villa del Rosario')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 57, 'Villa Elisa')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 58, 'Villa Hernandarias')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 59, 'Villa Mantero')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 60, 'Villa María Grande')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 61, 'Villa Paranacito')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 62, 'Villa Urquiza')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (8, 63, 'Villaguay')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (9, 1, 'Clorinda')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (9, 2, 'Comandante Fontana')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (9, 3, 'El Colorado')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (9, 4, 'Espinillo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (9, 5, 'Estanislao del Campo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (9, 6, 'Formosa')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (9, 7, 'General Enrique Mosconi')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (9, 8, 'Herradura')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (9, 9, 'Ibarreta')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (9, 10, 'Ingeniero Guillermo N. Juárez')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (9, 11, 'Laguna Naick-Neck')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (9, 12, 'Laguna Yema')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (9, 13, 'Las Lomitas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (9, 14, 'Palo Santo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (9, 15, 'Pirané')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (9, 16, 'Pozo del Tigre')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (9, 17, 'Riacho Eh-Eh')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (9, 18, 'San Francisco de Laishí')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (9, 19, 'Villa Escolar')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 1, 'Abra Pampa')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 2, 'Caimancito')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 3, 'Calilegua')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 4, 'El Aguilar')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 5, 'El Carmen')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 6, 'Fraile Pintado')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 7, 'Humahuaca')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 8, 'Ingenio La Esperanza')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 9, 'La Mendieta')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 10, 'La Quiaca')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 11, 'Libertador General San Martín')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 12, 'Maimará')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 13, 'Palma Sola')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 14, 'Palpalá')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 15, 'Rinconada')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 16, 'San Antonio')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 17, 'San Pedro')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 18, 'San Salvador de Jujuy')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 19, 'Santa Catalina')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 20, 'Santa Clara')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 21, 'Susques')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 22, 'Tilcara')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 23, 'Tumbaya')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 24, 'Valle Grande')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (10, 25, 'Yuto')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 1, 'Algarrobo del Águila')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 2, 'Alpachiri')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 3, 'Alta Italia')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 4, 'Anguil')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 5, 'Arata')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 6, 'Bernardo Larroudé')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 7, 'Bernasconi')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 8, 'Caleufú')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 9, 'Catriló')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 10, 'Colonia Barón')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 11, 'Cuchillo Có')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 12, 'Doblas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 13, 'Eduardo Castex')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 14, 'Embajador Martini')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 15, 'General Acha')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 16, 'General Manuel J. Campos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 17, 'General Pico')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 18, 'General San Martín')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 19, 'Guatraché')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 20, 'Ingeniero Luiggi')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 21, 'Intendente Alvear')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 22, 'Jacinto Arauz')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 23, 'La Maruja')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 24, 'Limay Mahuida')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 25, 'Lonquimay')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 26, 'Macachín')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 27, 'Miguel Riglos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 28, 'Parera')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 29, 'Puelches')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 30, 'Quemú Quemú')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 31, 'Rancul')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 32, 'Realicó')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 33, 'Santa Isabel')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 34, 'Santa Rosa')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 35, 'Telén')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 36, 'Toay')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 37, 'Trenel')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 38, 'Uriburu')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 39, 'Veinticinco de Mayo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 40, 'Victorica')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (11, 41, 'Winifreda')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 1, 'Aimogasta')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 2, 'Aminga')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 3, 'Arauco')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 4, 'Castro Barros')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 5, 'Chamical')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 6, 'Chepes')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 7, 'Chilecito')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 8, 'Famatina')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 9, 'La Rioja')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 10, 'Malanzán')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 11, 'Milagro')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 12, 'Olta')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 13, 'Patquía')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 14, 'San Blas de los Sauces')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 15, 'Sañogasta')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 16, 'Tama')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 17, 'Ulapes')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 18, 'Villa Bustos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 19, 'Villa Castelli')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 20, 'Villa Unión')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (12, 21, 'Vinchina')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (13, 1, 'General Alvear')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (13, 2, 'General Lavalle')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (13, 3, 'Godoy Cruz')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (13, 4, 'Junín')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (13, 5, 'La Consulta')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (13, 6, 'La Paz')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (13, 7, 'Las Heras')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (13, 8, 'Luján de Cuyo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (13, 9, 'Maipú')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (13, 10, 'Malargüe')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (13, 11, 'Mendoza')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (13, 12, 'Rivadavia')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (13, 13, 'San Martín')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (13, 14, 'San Rafael')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (13, 15, 'Santa Rosa')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (13, 16, 'Tunuyán')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (13, 17, 'Tupungato')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (13, 18, 'Villa Nueva')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 1, 'Alba Posse')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 2, 'Almafuerte')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 3, 'Apóstoles')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 4, 'Aristóbulo del Valle')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 5, 'Arroyo del Medio')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 6, 'Azara')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 7, 'Bernardo de Irigoyen')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 8, 'Bonpland')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 9, 'Campo Grande')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 10, 'Campo Ramón')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 11, 'Campo Viera')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 12, 'Candelaria')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 13, 'Capioví')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 14, 'Caraguatay')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 15, 'Cerro Azul')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 16, 'Cerro Corá')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 17, 'Colonia Aurora')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 18, 'Colonia Wanda')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 19, 'Concepción de la Sierra')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 20, 'Dos Arroyos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 21, 'Dos de Mayo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 22, 'El Alcázar')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 23, 'El Soberbio')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 24, 'Eldorado')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 25, 'Florentino Ameghino')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 26, 'Garuhapé')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 27, 'Garupá')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 28, 'General Alvear')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 29, 'Gobernador Roca')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 30, 'Guaraní')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 31, 'Jardín América')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 32, 'Leandro N. Alem')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 33, 'Loreto')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 34, 'Los Helechos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 35, 'Mártires')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 36, 'Mojón Grande')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 37, 'Montecarlo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 38, 'Oberá')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 39, 'Panambí')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 40, 'Picada Gobernador López')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 41, 'Posadas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 42, 'Puerto Eldorado')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 43, 'Puerto Esperanza')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 44, 'Puerto Iguazú')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 45, 'Puerto Leoni')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 46, 'Puerto Libertad')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 47, 'Puerto Piray')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 48, 'Puerto Rico')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 49, 'Ruiz de Montoya')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 50, 'San Ignacio')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 51, 'San Javier')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 52, 'San José')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 53, 'San Pedro')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 54, 'San Vicente')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 55, 'Santa Ana')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 56, 'Santa María')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 57, 'Santo Pipó')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 58, 'Tres Capones')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (14, 59, 'Veinticinco de Mayo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 1, 'Aluminé')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 2, 'Andacollo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 3, 'Añelo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 4, 'Barrancas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 5, 'Buta Ranquil')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 6, 'Centenario')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 7, 'Chos Malal')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 8, 'Cutral-Có')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 9, 'El Huecú')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 10, 'Junín de los Andes')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 11, 'Las Coloradas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 12, 'Las Lajas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 13, 'Las Ovejas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 14, 'Loncopué')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 15, 'Mariano Moreno')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 16, 'Neuquén')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 17, 'Picún Leufú')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 18, 'Piedra del Águila')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 19, 'Plaza Huincul')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 20, 'Plottier')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 21, 'San Martín de los Andes')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 22, 'Senillosa')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 23, 'Villa La Angostura')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 24, 'Vista Alegre')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (15, 25, 'Zapala')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 1, 'Allen')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 2, 'Catriel')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 3, 'Cervantes')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 4, 'Chichinales')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 5, 'Chimpay')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 6, 'Choele Choel')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 7, 'Cinco Saltos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 8, 'Cipolletti')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 9, 'Comallo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 10, 'Contraalmirante Cordero')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 11, 'Coronel Belisle')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 12, 'Darwin')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 13, 'El Bolsón')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 14, 'El Cuy')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 15, 'Fray Luis Beltrán')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 16, 'General Conesa')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 17, 'General Enrique Godoy')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 18, 'General Fernández Oro')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 19, 'General Roca')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 20, 'Ingeniero Jacobacci')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 21, 'Ingeniero Luis A. Huergo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 22, 'Lamarque')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 23, 'Los Menucos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 24, 'Mainque')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 25, 'Maquinchao')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 26, 'Ñorquinco')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 27, 'Pilcaniyeu')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 28, 'Río Colorado')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 29, 'San Antonio Oeste')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 30, 'San Carlos de Bariloche')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 31, 'Sierra Colorada')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 32, 'Sierra Grande')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 33, 'Valcheta')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 34, 'Viedma')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (16, 35, 'Villa Regina')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 1, 'Apolinario Saravia')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 2, 'Cachí')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 3, 'Cafayate')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 4, 'Campo Quijano')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 5, 'Cerrillos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 6, 'Chicoana')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 7, 'El Carril')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 8, 'El Galpón')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 9, 'El Quebrachal')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 10, 'Embarcación')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 11, 'General Enrique Mosconi')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 12, 'General Martín Miguel de Güemes')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 13, 'Guachipas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 14, 'Iruya')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 15, 'Joaquín V. González')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 16, 'La Caldera')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 17, 'La Candelaria')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 18, 'La Poma')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 19, 'La Viña')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 20, 'Las Lajitas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 21, 'Metán')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 22, 'Molinos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 23, 'Rivadavia')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 24, 'Rosario de la Frontera')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 25, 'Rosario de Lerma')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 26, 'Salta')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 27, 'San Antonio de los Cobres')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 28, 'San Carlos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 29, 'San Ramón de la Nueva Orán')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 30, 'Santa Rosa de Tastil')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 31, 'Santa Victoria')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (17, 32, 'Tartagal')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 1, 'Albardón')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 2, 'Calingasta')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 3, 'Caucete')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 4, 'Chimbas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 5, 'Nueve de Julio')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 6, 'Pocito')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 7, 'Rivadavia')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 8, 'Rodeo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 9, 'San Agustín de Valle Fértil')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 10, 'San José de Jáchal')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 11, 'San Juan')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 12, 'San Martín')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 13, 'Santa Lucía')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 14, 'Tamberías')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 15, 'Villa Aberastain')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 16, 'Villa Basilio Nievas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 17, 'Villa del Salvador')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 18, 'Villa Krause')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 19, 'Villa Media Agua')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 20, 'Villa Paula de Sarmiento')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 21, 'Villa San Isidro')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (18, 22, 'Villa Santa Rosa')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (19, 1, 'Buena Esperanza')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (19, 2, 'Candelaria')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (19, 3, 'Concarán')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (19, 4, 'Justo Daract')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (19, 5, 'La Punta')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (19, 6, 'La Toma')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (19, 7, 'Libertador General San Martín')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (19, 8, 'Luján')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (19, 9, 'Merlo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (19, 10, 'Naschel')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (19, 11, 'San Francisco del Monte de Oro')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (19, 12, 'San Luis')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (19, 13, 'Santa Rosa del Conlara')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (19, 14, 'Tilisarao')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (19, 15, 'Unión')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (19, 16, 'Villa General Roca')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (19, 17, 'Villa Mercedes')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (20, 1, '28 de Noviembre')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (20, 2, 'Caleta Olivia')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (20, 3, 'Comandante Luis Piedra Buena')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (20, 4, 'El Calafate')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (20, 5, 'Gobernador Gregores')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (20, 6, 'Las Heras')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (20, 7, 'Los Antiguos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (20, 8, 'Perito Moreno')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (20, 9, 'Pico Truncado')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (20, 10, 'Puerto Deseado')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (20, 11, 'Puerto Santa Cruz')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (20, 12, 'Río Gallegos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (20, 13, 'Río Turbio')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (20, 14, 'San Julián')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (20, 15, 'Yacimiento Río Turbio')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 1, 'Armstrong')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 2, 'Arroyo Seco')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 3, 'Arrufó')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 4, 'Avellaneda')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 5, 'Bella Italia')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 6, 'Calchaquí')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 7, 'Cañada de Gómez')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 8, 'Capitán Bermúdez')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 9, 'Carcarañá')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 10, 'Casilda')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 11, 'Ceres')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 12, 'Chañar Ladeado')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 13, 'Coronda')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 14, 'El Trébol')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 15, 'Esperanza')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 16, 'Firmat')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 17, 'Fray Luis A. Beltrán')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 18, 'Funes')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 19, 'Gálvez')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 20, 'Gobernador Gálvez')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 21, 'Granadero Baigorria')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 22, 'Helvecia')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 23, 'Hersilia')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 24, 'Laguna Paiva')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 25, 'Las Parejas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 26, 'Las Rosas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 27, 'Las Toscas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 28, 'Malabrigo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 29, 'Melincué')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 30, 'Pérez')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 31, 'Rafaela')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 32, 'Reconquista')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 33, 'Recreo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 34, 'Roldán')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 35, 'Rosario')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 36, 'Rufino')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 37, 'San Carlos Centro')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 38, 'San Cristóbal')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 39, 'San Javier')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 40, 'San Jorge')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 41, 'San Justo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 42, 'San Lorenzo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 43, 'Santa Fe de la Vera Cruz')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 44, 'Santo Tomé')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 45, 'Sastre')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 46, 'Sunchales')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 47, 'Tostado')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 48, 'Totoras')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 49, 'Venado Tuerto')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 50, 'Vera')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 51, 'Villa Cañás')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 52, 'Villa Constitución')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 53, 'Villa Ocampo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (21, 54, 'Villa Trinidad')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 1, 'Añatuya')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 2, 'Arraga')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 3, 'Bandera')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 4, 'Beltrán')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 5, 'Brea Pozo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 6, 'Campo Gallo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 7, 'Clodomira')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 8, 'Colonia Dora')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 9, 'El Hoyo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 10, 'El Simbolar')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 11, 'Fernández')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 12, 'Frías')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 13, 'Garza')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 14, 'Herrera')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 15, 'La Banda')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 16, 'La Cañada')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 17, 'Los Juríes')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 18, 'Los Telares')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 19, 'Monte Quemado Airport')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 20, 'Nueva Esperanza')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 21, 'Pampa de los Guanacos')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 22, 'Pozo Hondo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 23, 'Quimilí')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 24, 'San Pedro')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 25, 'Santiago del Estero')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 26, 'Selva')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 27, 'Sumampa')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 28, 'Suncho Corral')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 29, 'Termas de Río Hondo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 30, 'Tintina')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 31, 'Villa Atamisqui')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 32, 'Villa General Mitre')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 33, 'Villa Ojo de Agua')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (22, 34, 'Villa Unión')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (23, 1, 'Río Grande')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (23, 2, 'Ushuaia')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (24, 1, 'Aguilares')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (24, 2, 'Alderetes')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (24, 3, 'Banda del Río Salí')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (24, 4, 'Bella Vista')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (24, 5, 'Burruyacú')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (24, 6, 'Concepción')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (24, 7, 'Famaillá')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (24, 8, 'Graneros')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (24, 9, 'La Cocha')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (24, 10, 'Monteros')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (24, 11, 'San Isidro de Lules')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (24, 12, 'San Miguel de Tucumán')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (24, 13, 'Simoca')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (24, 14, 'Tafí del Valle')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (24, 15, 'Tafí Viejo')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (24, 16, 'Trancas')
INSERT INTO #LOCALIDADES1 (idprovincia, idlocalidad, descripcion) VALUES (24, 17, 'Yerba Buena')

--Creacion de la tabla temporal #TempLocalidades con un millon de registros con un id aleatorio de 1 a 966.
SELECT TOP 1000000
	CAST(966 * RAND(CHECKSUM(NEWID()))+1 AS INT) AS localidad1
INTO #TempLocalidades
FROM sys.all_objects a
CROSS JOIN sys.all_objects b;

--Insercion del millon de registros en la tabla gastoNew.
INSERT INTO gastoNew(idprovincia, idlocalidad, idconsorcio, periodo, fechapago, idtipogasto, importe)
SELECT TOP 1000000
	b.idprovincia AS idprovincia,
	b.idlocalidad AS idlocalidad,
	CAST(10 * RAND(CHECKSUM(NEWID()))+1 AS INT) AS idconsorcio,
	CAST(12 * RAND(CHECKSUM(NEWID()))+1 AS INT) AS periodo,
	DATEADD(day,CAST(5000 * RAND(CHECKSUM(NEWID()))+1 AS INT), '2010-01-01') AS fechapago,
	CAST(5 * RAND(CHECKSUM(NEWID()))+1 AS INT) AS idtipogasto,
	CAST(100000 * RAND(CHECKSUM(NEWID()))+100 AS DECIMAL(8,2)) AS importe
FROM #TempLocalidades a
JOIN #LOCALIDADES1 b
	ON a.localidad1 = b.idrow;

--Ver todos los registros la tabla gastoNew.
SELECT * FROM gastoNew;
